### ISSUE TITLE
Package 'panda_moveit_config' not found

### ISSUE THREAD

**Issue by LeonYo153** [AndrejOrsula/pymoveit2#63]
Excuse me Sir,
I noticed there is no panda_moveit_config in your package, thus i can't run the examples. Where can I get that?

**Comment by AndrejOrsula** [comment]
Hello,
This repository is robot invariant, so there are no robot-specific packages. The examples in [README](https://github.com/AndrejOrsula/pymoveit2?tab=readme-ov-file#examples) already contain links to the mentioned packages and where to get them.
- `panda_ign_moveit2` (<https://github.com/AndrejOrsula/panda_ign_moveit2>)
- `ign_moveit2_examples` (<https://github.com/AndrejOrsula/ign_moveit2_examples>)

**Comment by LeonYo153** [comment]
Thank you very much
