### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by shuhaowu** [AndrejOrsula/pymoveit2#7]
What's the license for this repo?

**Comment by AndrejOrsula** [comment]
Hello @shuhaowu,

It is Apache 2.0 as recommended by https://docs.ros.org/en/rolling/Contributing/Developer-Guide.html.

https://github.com/AndrejOrsula/pymoveit2/blob/70f8e001b3de0167efb351e28ccfeec488534d5b/package.xml#L8
