### ISSUE TITLE
get pre_configurated joint from moveit conifg

### ISSUE THREAD

**Issue by adamanov** [AndrejOrsula/pymoveit2#72]
Hello, first of all, thanks for the cool repo, and for providing the Python binding with Moveit on Humble. 

in moveit1 there was the following two function
```
arm = MoveGroupCommander("arm")
arm.set_named_target("home")
arm.go()

```
```
    <group_state name="home" group="arm">
        <joint name="joint1" value="0" />
        <joint name="joint2" value="-1.309" />
        <joint name="joint3" value="-0.261799" />
        <joint name="joint4" value="0" />
        <joint name="joint5" value="1.5708" />
        <joint name="joint6" value="0" />
    </group_state>
```

by setting the `home`  referring joints configuration inside the `.srdf ` file, it was super easy to move to a pre-defined target pose.

I was searching, a way how to do it with help of your package `pymoveit2`, and I found only the `move_to_configuration()` function which allows moving to a joint position, however, I am not able to move directly to get joint angles which I defined inside `.srdf`, is there any way to get them from moviet config? without hard- coding inside the my application node?

All best

**Comment by AndrejOrsula** [comment]
Hello @adamanov,

The codebase does not actually parse URDF/SRDF configs and afaik MoveIt 2 does not expose the list of named configurations via ROS 2. Therefore, there is currently no way to use them through `pymoveit2`.

**Comment by adamanov** [comment]
> Hello @adamanov,
> 
> The codebase does not actually parse URDF/SRDF configs and afaik MoveIt 2 does not expose the list of named configurations via ROS 2. Therefore, there is currently no way to use them through `pymoveit2`.

thanks for reply, i ended up also migrated on ros2 rolling to install moveit2 with python binding...
